### PR TITLE
adding Feature branch to the main brach for protifolio website

### PR DESCRIPTION
**Pull request by Fentahunn**
mobile first portfolio project.

### CODE REVIEW

**Review by Ofarouq310 — COMMENTED** [review]
Hi @Fentahunn  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

giphy

## 🔴 Invalid Code Review Request  

- You did not add the custom README yet, please use this [template](https://github.com/microverseinc/readme-template).
- Please Add a descriptive PR summary, and rename your branch to be more descriptive of your added features.
- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fentahunn** [comment]
Pull Request for "Portfolio: Setup and Mobile-First" Project

Description:
This pull request adds the necessary changes to implement the "Portfolio: Setup and Mobile-First" project. The project focuses on creating a developer's portfolio website, showcasing the work of fentahun agmas. 

This pull request addresses any previously identified issues, such as missing documentation or incorrect branch naming, and provides a comprehensive solution for the project requirements.

Please review  this pull request  of the "Portfolio: Setup and Mobile-First" project.

Changes:

Added responsive design using a mobile-first approach
Integrated specific social media links and descriptions
Organized code and ensured semantic HTML structure
Implemented CSS styling to optimize the user experience
Addressed previously identified issues (missing README.md file, incorrect branch naming)
Thank you for your attention and feedback.

**Review by Ofarouq310 — COMMENTED** [review]
Hi @Fentahunn , ✋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 🥈 

giphy

## 🔴 Invalid Code Review Request  

- Your branch should have a name of a feature or action you are implementing, in your case it could be "mobile-setup" or "header-and-deadline" or whatever suits you. Kindly fix it and rename your branch. Kindly refer to the next image for the steps of renaming a branch.
image


- Your Pull request title should be short, and concise, and addresses what you are implementing, in your case, it could be, `Add header and headline sections` or something similar, simpler. Please refer to the next picture to help you how to edit the title.
image

-  As for the PR description, you should simplify it even more, just summarizing what you added in a bullet list or number list, take a look at this example, to edit the description, just click on three dots on the right side, then click on edit.
image



- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by amon-cofie — CHANGES_REQUESTED** [review]
Hi @Fentahunn , 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have evidently done great work on this project but lets talk a little about what the previous reviewer meant 💪. I can see that you added your PR summary as a comment but the reviewer was drawing your attention to the fact that there is a place where your PR summary goes and it is at the very top of the PR (I will leave a screenshot below). What we can do is copy the content of the summary you gave as a comment and paste it in the appropriate space. To edit the PR summary, you need to click the three dots in the top right corner and select on edit in the drop-down. Now you can paste your PR summary 😉.  

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
